# Generated by Django 3.1.7 on 2021-03-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seach',
            new_name='Search',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='seach',
            new_name='search',
        ),
    ]
